version: "3.2"

services:
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    dns_search: "" # For Mac smoothness
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - pinlink
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    networks:
      - pinlink
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017

networks:
  pinlink:
